// This file was autogenerated by calcdeps.py
goog.addDependency("../../../js/app_init.js", [], ['goog.module.ModuleLoader', 'goog.module.ModuleManager', 'fastmock.ModulesInfo', 'fastmock.app']);
goog.addDependency("../../../js/modules_info.js", ['fastmock.ModulesInfo'], []);
goog.addDependency("../../../js/deps.js", [], []);
goog.addDependency("../../../js/dummy.js", ['dummy'], ['goog.ui.CustomButton', 'goog.module.ModuleLoader', 'goog.module.ModuleManager']);
goog.addDependency("../../../js/app.js", ['fastmock.app'], ['goog.events', 'goog.dom', 'goog.cssom']);
goog.addDependency("../../../js/loaded_module_css.js", [], ['goog.cssom']);
goog.addDependency("../../../js/loaded_module.js", ['fastmock.loaded_module'], ['goog.ui.CustomButton', 'goog.dom']);
goog.addDependency("../../../js/loaded_module_init.js", [], ['goog.module.ModuleManager', 'fastmock.loaded_module']);
